version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      # As variáveis virão do seu arquivo .env local
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - DEST_1=${DEST_1}
      - DEST_2=${DEST_2}
    restart: unless-stopped